padre(enrique7,arturo).
padre(enrique7,margarita).
padre(enrique7,enrique8).
padre(enrique8,catalina).
padre(enrique8,juana).
padre(enrique8,ana).
abuelo(enrique7,catalina).
abuelo(enrique7,juana).
abuelo(enrique7,ana).
abuelo(enrique8,maria).
abuelo(enrique8,isabel).
abuelo(enrique8,eduardo).
hermana(margarita,enrique8).
hermano(arturo,enrique8).
hermana(catalina,juana).
hermana(ana,catalina).
hermana(maria,isabel).
hermana(maria,eduardo).
hermano(eduardo,maria).
hermano(eduardo,isabel).
hermana(isabel,maria).
hermana(isabel,eduardo).
hombre(enrique7).
hombre(arturo).
hombre(enrique8).
hombre(eduardo).
mujer(margarita).
mujer(catalina).
mujer(juana).
mujer(ana).
mujer(maria).
mujer(isabel).